### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by BoyuanJiang** [mosaicml/diffusion#10]
i try to run train with composer run.py --config_path yamls/hydra-yamls --config_name SD-2-base-256.yaml but got following error
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/16739780/236601063-1c0fc9cd-2b75-4cd0-a589-09295a9508ea.png">

**Comment by Landanjs** [comment]
Thanks for trying out our repo and reporting this issue! Ah, we made a last minute mistake with the Hydra command-line 😞 The fix is #11. Once this merged please let use know if you still have issues
