### ISSUE TITLE
What is the benefit of multi phase training?

### ISSUE THREAD

**Issue by PhucLee2605** [mosaicml/diffusion#103]
Hi, thank all of you guys for releasing such a masterpiece on training SD.

Currently, I am wondering what is the benefit of training SD with 2 phases (256 and 512 in size). Is the first stage like a warm-up or something? What if I start directly with 512x512 training images?

I am researching SD and it is awesome to dive into training techniques.

Hope to get a reply soon. 
Peace.

**Comment by coryMosaicML** [comment]
Training at 256x256 is much quicker than training at 512x512, so you can get through the initial phase where the network is still learning to generate plausible images while using less compute. Once the network learns how to generate plausible low resolution images and follow the prompt, it takes far fewer training iterations to adapt to generating high resolution images compared to training at high resolution from the start.

In the case of architectures like SD1/SD2, there's also the benefit of being able to make use of more data at the lower resolution without having to upsample. This isn't true for SDXL though, as it is conditioned on the image size and uses the lower resolution images during training already.

**Comment by PhucLee2605** [comment]
Thanks for your response. 

I'm glad that your answer is similar to what I'm thinking.

Seems like it is all about the optimization of training resources.
