### ISSUE TITLE
inference code?

### ISSUE THREAD

**Issue by BoyuanJiang** [mosaicml/diffusion#16]
hello, can you provide a script to convert a trained model to diffusers ckpt format so I can inference my trained model using diffusers?

**Comment by Landanjs** [comment]
Hello! If I understand your use case correctly, you want to convert the weights checkpoint generated from this repo into a checkpoint that can be used with `StableDiffusionPipeline.from_pretrained()`? Or is there a different class you want to use?

**Comment by BoyuanJiang** [comment]
yes, I want to convert the generated weight so I can load it with StableDiffusionPipeline.from_pretrained()

**Comment by Landanjs** [comment]
Thanks for the info, we will setup a script and send it over!

**Comment by Landanjs** [comment]
Apologies for the delay! Since this repo, uses diffusers, it's easy to convert the checkpoint. Below is code snippet to save a checkpoint the can be loaded from `StablediffusionPipeline.from_pretrained()`. Let me know if you have any issues!

```
import argparse

import torch
from diffusers import StableDiffusionPipeline

from diffusion.models import stable_diffusion_2

parser = argparse.ArgumentParser()
parser.add_argument('--load_path', type=str, required=True, help='Path to the checkpoint to convert.')
parser.add_argument('--save_path', type=str, required=True, help='Path to save the converted checkpoin.')
args = parser.parse_args()

def main(args):
    model = stable_diffusion_2(pretrained=False, train_metrics=[], val_metrics=[])

    ckpt = torch.load(args.load_path, map_location="cpu")

    model.load_state_dict(ckpt["state"]["model"])

    pipe = StableDiffusionPipeline(
        vae=model.vae,
        text_encoder=model.text_encoder,
        tokenizer=model.tokenizer,
        unet=model.unet,
        scheduler=model.inference_scheduler,
        safety_checker=None,
        feature_extractor=None,
        requires_safety_checker=False,
    )
    pipe.save_pretrained(args.save_path)

if __name__ == "__main__":
    main(args)
```

**Comment by BoyuanJiang** [comment]
It works, thanks for the reply!
