### ISSUE TITLE
some question about learning rate

### ISSUE THREAD

**Issue by BoyuanJiang** [mosaicml/diffusion#17]
In SD-256.yaml, the learning rate is set to 1e-4, I wonder whether the learning rate will be scaled up with the increase of GPUs. For example, if I use 64 GPUs train the model, will the learning rate be scaled to 64*1e-4 automatically?

**Comment by mvpatel2000** [comment]
@BoyuanJiang the learning rate should be the same regardless of the number of GPUs. In our code, you will get the same training curve regardless of if you use 1 or 64 (or any other number) of GPUs.
