### ISSUE TITLE
Question regarding the training dataset

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#19]
Hope this finds you well. Very amazing work!!!
As mentioned in https://github.com/mosaicml/diffusion#how-many-gpus-do-i-need, "Our time estimates are based on training Stable Diffusion 2.0 base on 1,126,400,000 images at 256x256 resolution and 1,740,800,000 images at 512x512 resolution". 
I have three questions:
1) since the whole data of [ChristophSchuhmann/improved_aesthetics_4.5plus](https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_4.5plus/tree/main) is 1.2B, how come that you have 1.74B images with original resolution > 512x512?
2) I am also downloading [ChristophSchuhmann/improved_aesthetics_4.5plus](https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_4.5plus/tree/main), but it turns out that the failed ratio is about 20%, which means I can only get about 960M images. How could you download 1.12B images at 256x256 resolution? I follow the downloading script provided in this repo.
3) According to [stabilityai/stable-diffusion-2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base), they said "The model is trained from scratch 550k steps at resolution 256x256 on a subset of [LAION-5B](https://laion.ai/blog/laion-5b/) filtered for explicit pornographic material, using the [LAION-NSFW classifier](https://github.com/LAION-AI/CLIP-based-NSFW-Detector) with punsafe=0.1 and an [aesthetic score](https://github.com/christophschuhmann/improved-aesthetic-predictor) >= 4.5. Then it is further trained for 850k steps at resolution 512x512 on the same dataset on images with resolution >= 512x512". Have you applied punsafe=0.1 in your training? I suppose "punsafe=0.1" means that we only use samples with punsafe<0.1, am I correct?

Thanks very much!!!

**Comment by mvpatel2000** [comment]
> 1. since the whole data of [ChristophSchuhmann/improved_aesthetics_4.5plus](https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_4.5plus/tree/main) is 1.2B, how come that you have 1.74B images with original resolution > 512x512?
We use multiple epochs, so some data is repeated
> 2. I am also downloading [ChristophSchuhmann/improved_aesthetics_4.5plus](https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_4.5plus/tree/main), but it turns out that the failed ratio is about 20%, which means I can only get about 960M images. How could you download 1.12B images at 256x256 resolution? I follow the downloading script provided in this repo.
We see a failure rate around that. Depending on your internet settings, IP address, VPN, etc, you may get higher or lower failure rates. This is because some links from LAION are either now broken or are blocking you. I think this is probably fine. We also repeat data at 256x256 resolution
> 3. According to [stabilityai/stable-diffusion-2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base), they said "The model is trained from scratch 550k steps at resolution 256x256 on a subset of [LAION-5B](https://laion.ai/blog/laion-5b/) filtered for explicit pornographic material, using the [LAION-NSFW classifier](https://github.com/LAION-AI/CLIP-based-NSFW-Detector) with punsafe=0.1 and an [aesthetic score](https://github.com/christophschuhmann/improved-aesthetic-predictor) >= 4.5. Then it is further trained for 850k steps at resolution 512x512 on the same dataset on images with resolution >= 512x512". Have you applied punsafe=0.1 in your training? I suppose "punsafe=0.1" means that we only use samples with punsafe<0.1, am I correct?
@Landanjs  can correct me, but I do not think we did this data filtering step. If you would like to do so, you can do it in the upload script (mds writer) by adding an if statement conditioned on that field

**Comment by viyjy** [comment]
Thanks. May I know how many images have you downloaded? Since I want to use your code to reproduce the result you reported, trying to make sure my data is not the potential issue.

**Comment by Landanjs** [comment]
For images with resolution >= 256x256, we have ~790 million image-caption pairs. For images with resolution >= 512x512, we had ~300 million image-caption pairs.

Also, Mihir was correct, we did not do any punsafe or pwatermark filtering. I agree with you that `punsafe=0.1` likely means `punsafe<0.1`, but definitely check with stability folks.

**Comment by viyjy** [comment]
Thanks. I mean the total number of images, including all resolutions. Do you have this number?

**Comment by viyjy** [comment]
BTW, you only use the images with original resolution >= 256*256 in the stage 1 training? I thought we should use all images in stage 1, just resize them to 256*256 according to [stabilityai/stable-diffusion-2-base](https://huggingface.co/stabilityai/stable-diffusion-2-base)

**Comment by Landanjs** [comment]
We had ~1.2 billion image-text pairs total. 

We suspected some correlation between aesthetic score and image resolution and that resizing the low resolution images could generate a lot of artifacts, so we only trained on >= 256x256.

**Comment by viyjy** [comment]
One more question: when we are talking about the original image size (H, W) >= 256\*256, does it mean H>=256 and W>256 or just H\*W >= 256\*256? Thanks in advance!

**Comment by Landanjs** [comment]
The former, both H and W are >= 256

**Comment by viyjy** [comment]
Many thanks!!!
