### ISSUE TITLE
No initialize_dist in precompute_latent.py

### ISSUE THREAD

**Issue by DiegoD94** [mosaicml/diffusion#22]
I got this error running mainline precompute_latent.py with composer,
```
RuntimeError: The world_size(8) > 1, but the distributed package is not available or has not been initialized. Please check y$
u have initialized the distributed runtime and that PyTorch has been built with distributed support. If calling this function
outside Trainer, please ensure that `composer.utils.dist.initialize_dist` has been called first.
```
My understanding is that I need add dist.intialize_dist(device, timeout) right after get_device()
is this understanding correct? Thanks

**Comment by mvpatel2000** [comment]
@DiegoD94 thanks for flagging this! I believe that's correct, it looks like we're missing `dist.initialize_dist`. If you call 
```
from composer.utils import dist

dist.initialize_dist('gpu')
```
that should work. Let me know if you have any issues!

**Comment by DiegoD94** [comment]
Thanks!
