### ISSUE TITLE
can we use coco_captions dataset to train your model？？？

### ISSUE THREAD

**Issue by dreamlychina** [mosaicml/diffusion#25]
Thanks for sharing this amizing work，the LAION-5B is too big and i want  use coco_captions dataset to train the model, should i change the dataloader script coco_captions.py?

**Comment by Landanjs** [comment]
I think `StreamingCOCOCaptions` should work for both the train and val sets of COCO. You can likely use `build_streaming_cocoval_dataloader` as the `train_dataset._target_:`  in the `yamls/hydra-yamls`. You may want to make some tweaks to the build function such as adding more transformation.

**Comment by Landanjs** [comment]
Closing, feel free to re-open if there are additional questions
