### ISSUE TITLE
Are you planning releasing the trained model?

### ISSUE THREAD

**Issue by ivanprado** [mosaicml/diffusion#26]
I see it referenced in the source code as `oci://mosaicml-internal-checkpoints/stable-diffusion-hero-run/4-13-512-ema/ep5-ba850000-rank0.pt`. It would be nice to try it.

**Comment by Landanjs** [comment]
Unfortunately, due to the [legal issues](https://www.theverge.com/2023/1/17/23558516/ai-art-copyright-stable-diffusion-getty-images-lawsuit) around LAION, the dataset used to train Stable Diffusion, we are unable to release weights.

**Comment by densechen** [comment]
Can we just load the public stable diffusion v2.0's weight and do a finetune training?

**Comment by mvpatel2000** [comment]
@densechen  yes that should work
