### ISSUE TITLE
FID score is weird

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#31]
Hi, I add FID (val_guidance_scales: [3.0]) as one of the eval metrics, but the FID score is quite strange shown below. It starts from about 1. I use 8 GPUs with total batch size 128=16*8.
![image](https://github.com/mosaicml/diffusion/assets/20442927/4ba361e8-7f03-41ce-b819-5731e61729d0)

The loss looks good
![image](https://github.com/mosaicml/diffusion/assets/20442927/7113982d-08be-48d6-b07b-d1b7dda76185)

**Comment by viyjy** [comment]
Update: I use this [script](https://github.com/mosaicml/diffusion/blob/main/scripts/fid-clip-evaluation.py) to evaluate saved checkpoints and seems like the FID is reasonable. However, the FID calculated during the training is still strange as shown below:
![image](https://github.com/mosaicml/diffusion/assets/20442927/957282f2-0dea-4deb-b5ee-eff8fb0a426a)

**Comment by coryMosaicML** [comment]
Hmm, which dataset are you using for eval during training? Is it the same as the one you used with the script?

**Comment by viyjy** [comment]
Sorry for the late reply, I am using COCO2014
