### ISSUE TITLE
upsample_nearest_nhwc only supports output tensors with less than int_max

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#43]
Hi, I get the following error when I use [fid-clip-evaluation.py](https://github.com/mosaicml/diffusion/blob/main/scripts/fid-clip-evaluation.py) with size=512, but it works with size=256. Any suggestions? Thanks.

![image](https://github.com/mosaicml/diffusion/assets/20442927/eacd90df-97a1-4585-abdc-19a07a8daf71)

**Comment by coryMosaicML** [comment]
I think this might be due to a limitation in the upsampling implementation used in the decoder VAE. As a workaround, lowering the batch size you're using for eval should unblock you in the short term if you need something quickly.

**Comment by viyjy** [comment]
@coryMosaicML Thanks, but I get the same error even with batch size=8. It was 16.

**Comment by coryMosaicML** [comment]
Hmm, can you provide a bit of information about your setup, and how you're calling the eval script so that I can try to reproduce this?

**Comment by viyjy** [comment]
sure, I am using the following command:
```
composer fid-clip-evaluation.py \
--remote path/of/MDS_val2014/ \
--load_path path/of/checkpoint/ \
--guidance_scale 7.0 \
--size 512 \
--batch_size 8 \
--seed 17 \
```

**Comment by coryMosaicML** [comment]
Thanks! Can you share which PyTorch version you're using?

**Comment by viyjy** [comment]
I have tried 2.0.1 and 1.13.1, both give the same error

**Comment by coryMosaicML** [comment]
Unfortunately I'm not able to reproduce this error on my end. One more thing to try might be reducing batch size to 4 rather than 8 as a workaround. Are you using our docker image (`mosaicml/pytorch_vision:1.13.1_cu117-python3.10-ubuntu20.04`) and hitting this?
