### ISSUE TITLE
save_overwrite conflicts with autoresume=true

### ISSUE THREAD

**Issue by s5248** [mosaicml/diffusion#48]
When must set autoresume=true,
if I set save_overwrite = false，it says:

> FileExistsError: /home/mnt/diffmodels/ep0-ba1000-rank0.pt may conflict with a future checkpoint of the current run.Please
delete that file, change to a new folder, or **set overwrite=True**.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: ð View run sd-model at: https://wandb.ai/xxxx/diffusion/runs/hpzkfedp
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230701_152030-hpzkfedp/logs

if I set save_overwrite = true, it says:

> InstantiationException: Error in call to target 'composer.trainer.trainer.Trainer':
ValueError('The flag **`save_overwrite` must be False when autoresume is enabled as autoresume always loads the latest existing checkpoint in `save_folder`**. ')
full_key: trainer

**Comment by mvpatel2000** [comment]
Unfortunately, this is a requirement for using autoresume. You are welcome to turn off autoresume if you would like, but in the future you will have to manually specify the load path when continuing a training run.
