### ISSUE TITLE
How can I improve to solve this problem?

### ISSUE THREAD

**Issue by YMKiii** [mosaicml/diffusion#60]
Error executing job with overrides: []
Error locating target 'diffusion.datasets.laion.laion.build_streaming_laion_dataloader', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: dataset.train_dataset

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 16072) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 16072) exited with code 1

**Comment by coryMosaicML** [comment]
This is happening because something is causing the train dataset to crash on initialization. If you set the environment variable via `export HYDRA_FULL_ERROR=1` you should get a more detailed message that can help with debugging. Can you give that a try and show the message you get?

**Comment by YMKiii** [comment]
How do I set this environment variable?
export HYDRA_FULL_ERROR=1

**Comment by Landanjs** [comment]
Yes, `export HYDRA_FULL_ERROR=1`

**Comment by YMKiii** [comment]
The variables are set but that's still the question

ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 22148) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 22148) exited with code 1

Is this training code only run on the A100?

**Comment by Landanjs** [comment]
Setting `export HYDRA_FULL_ERROR=1` should provide a more extensive traceback on the error you are hitting. Can you provide your full logs / traceback? The snippet isn't info for us to help debug.

We've run this code on A100s and H100s, what hardware are you running on?

**Comment by YMKiii** [comment]
Nvidia 4090 
I want to do a quick test. Does this hardware work

**Comment by YMKiii** [comment]
Does it at least work on the A100?

**Comment by YMKiii** [comment]
Hello, the configuration log is as follows:
I changed tokenizer_name_or_path in lain.py: str =" local data set path"
By the way, what should the training set format look like?
Second, we also modified the data set path of the SD-2-base-256.yaml file and made it local
CUDA Version: 12.2
The hardware is RTX 4090

**Comment by YMKiii** [comment]
Hello, thank you very much for your reply earlier. These training codes are very important to our company, so could you please tell me the minimum hardware requirements? So that we can make subsequent purchases

**Comment by YMKiii** [comment]
> This is happening because something is causing the train dataset to crash on initialization. If you set the environment variable via `export HYDRA_FULL_ERROR=1` you should get a more detailed message that can help with debugging. Can you give that a try and show the message you get?

**Comment by Landanjs** [comment]
We've tested the code on A100s and H100s, we have not tested 4090s. 

Our dataset code (`laion.py` and `image_caption.py`) assumes the data is in an MDS format (from our [streaming library](https://github.com/mosaicml/streaming)). We use a streaming format, so we can easily do large-scale training across multiple clouds. If you rather not use our streaming dataset, you can define a PyTorch dataset and dataloader for your data, then provide that class to the `train_dataset` field in the configuration yaml.

Here is a table from our [blog post
](https://www.mosaicml.com/blog/diffusion) outlining different training time / cost based on the amount of available of compute. Time / cost will also change based on the number of iterations / images you would like to train on .
![image](https://github.com/mosaicml/diffusion/assets/33618586/63dbd4b8-a0b9-4738-8232-4ebd4f576028)

**Comment by YMKiii** [comment]
Ok, thank you very much for your answer
