### ISSUE TITLE
Why do we load clip-vit-large-patch14?

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#68]
Hi, I was wondering why do I see the following log by using `stable_diffusion_2`? I didn't see the training code is supposed to load `openai--clip-vit-large-patch14`, isn't it?
```
mosaic/0 [0]:[INFO|configuration_utils.py:712] 2023-10-03 22:40:58,340 >> loading configuration file config.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/config.json
```

**Comment by jazcollins** [comment]
Hello! This is because `OpenCLIP ViT-H` is the text encoder used by Stable Diffusion 2. This line [here](https://github.com/mosaicml/diffusion/blob/main/diffusion/models/models.py#L91) will load that pre-trained model.

**Comment by viyjy** [comment]
@jazcollins Thanks. But the log show `openai--clip-vit-large-patch14`, not `OpenCLIP ViT-H`
I have set a breakpoint after this line https://github.com/mosaicml/diffusion/blob/main/diffusion/models/models.py#L69, and still can get this log
```
mosaic/0 [0]:[INFO|configuration_utils.py:712] 2023-10-03 22:40:58,340 >> loading configuration file config.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/config.json
```

**Comment by jazcollins** [comment]
Are you training Stable Diffusion 2 or Stable Diffusion XL? Stable Diffusion XL uses openai's `CLIP ViT-L` as one of its text encoders

**Comment by viyjy** [comment]
I am training Stable Diffusion 2

**Comment by viyjy** [comment]
I am using this training code https://github.com/mosaicml/diffusion/blob/main/diffusion/train.py

**Comment by jazcollins** [comment]
Got it. That does seem potentially strange. Can you share the `model` part of your training config params?

**Comment by viyjy** [comment]
I am using https://github.com/mosaicml/diffusion/blob/main/yamls/hydra-yamls/SD-2-base-256.yaml#L12

**Comment by viyjy** [comment]
This object instantiation will also print out something like:

```
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,323 >> loading file vocab.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/vocab.json
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,323 >> loading file merges.txt from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/merges.txt
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,324 >> loading file tokenizer.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/tokenizer.json
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,324 >> loading file added_tokens.json from cache at None
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,324 >> loading file special_tokens_map.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/special_tokens_map.json
mosaic/0 [0]:[INFO|tokenization_utils_base.py:1839] 2023-10-04 00:53:34,324 >> loading file tokenizer_config.json from cache at .cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41/tokenizer_config.json
```

**Comment by viyjy** [comment]
I found that removing `torchmetrics.multimodal.CLIPScore` from `val_metrics' solve the problem
