### ISSUE TITLE
Bug Report of image_caption.py

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#80]
This line of code https://github.com/mosaicml/diffusion/blob/main/diffusion/datasets/image_caption.py#L214 should be changed to 
```
crop_transform = RandomCropSquare(resize_size) if rand_crop else LargestCenterSquare(resize_size)
```

**Comment by Landanjs** [comment]
Thank you for reporting this! I'm sorry if this lead to any inconveniences. Fix in progress
