### ISSUE TITLE
missing index.json when excuting laion_cloudwriter.py

### ISSUE THREAD

**Issue by MingzhouZhang** [mosaicml/diffusion#9]
Nice work!

laion_cloudwriter.py conveted format sucessfully from parquet to mds, but failed to generate index.json file which is neccessary for dataloader in precompute_latents.py.

Is this a bug? Thanks for help.

**Comment by MingzhouZhang** [comment]
I'm idiot.

Because missing empty file which is created as "done" in laion_download_aesthetic.sh, laion_cloudwriter.py stuck in the unlimited loop. Interupt the program and index.json will not be created.

**Comment by mvpatel2000** [comment]
Glad you figured it out! Let us know if you need further assistance.

**Comment by Landanjs** [comment]
Did you already create lots of shards and would like to generate an `index.json` file without rerunning the download script? We have a script somewhere to build an `index.json` based on pre-existing shards. I can dig it up if it is useful! Hopefully it will be baked into the Streaming library in the future.

**Comment by viyjy** [comment]
@MingzhouZhang Hi, I have the same problem now and ask for your help.

>"laion_cloudwriter.py conveted format sucessfully from parquet to mds" 
How large of your dataset and how long does it take to finish the conversion? I have downloaded "ChristophSchuhmann/improved_aesthetics_4.5plus" which contains 1.1 billion samples (96TB) into my s3 bucket and working on the MDS conversion, but seems like it will take very long time to finish the conversion.

> Because missing empty file which is created as "done" in laion_download_aesthetic.sh
What is the missing empty fine? I didn't see this fine in my downloaded files

Thanks very much!!!
