### ISSUE TITLE
When is common canvas going to be released?

### ISSUE THREAD

**Issue by ninjasaid2k** [mosaicml/diffusion#91]

**Comment by Skylion007** [comment]
Working on the model card & dataset card right now. :)

**Comment by TruthSearcher** [comment]
I'm also wondering about this.

**Comment by Skylion007** [comment]
Working on it. :)

**Comment by ninjasaid2k** [comment]
Can you give me an expected time or release?

**Comment by Skylion007** [comment]
Reprocessing the data is taking bit longer than expected (huggingface needs all the files to be packed in a certain way for it accept such a large image dataset). Will try to get this out ASAP now that CVPR is over.

**Comment by olliacc** [comment]
> Can you give me an expected time window for release?
probably before christmas.

**Comment by TruthSearcher** [comment]
> > Can you give me an expected time window for release?
> 
> probably before christmas.

best christmas gift ever

**Comment by MHillier98** [comment]
Very interested as well!

**Comment by olliacc** [comment]
> Very interested as well!

🤷‍♂️

**Comment by hckr** [comment]
It would be great if you managed to release the model in 2023, [some people bet on it ](https://manifold.markets/LarsDoucet/will-an-ai-art-generator-be-trained?r=TXJMdWtlMjU1)😅

**Comment by Dibbidy** [comment]
> probably before christmas.

I would say we have about a week left before christmas, it seems unlikely.
> It would be great if you managed to release the model in 2023, [some people bet on it ](https://manifold.markets/LarsDoucet/will-an-ai-art-generator-be-trained?r=TXJMdWtlMjU1)😅

seems like a 56% chance of release. Fingers crossed.

**Comment by TruthSearcher** [comment]
@Skylion007 any news?

**Comment by ninjasaid2k** [comment]
> Reprocessing the data is taking bit longer than expected (huggingface needs all the files to be packed in a certain way for it accept such a large image dataset). Will try to get this out ASAP now that CVPR is over.

great work! hope to see it soon.

**Comment by olliacc** [comment]
> great work! hope to see it soon.

I'm sorry to tell you that they don't plan on ever releasing it.

**Comment by Skylion007** [comment]
Sorry, for the delay. Met with @apolinario at NeurIPS and we are working on a hosting solution for the dataset. We plan on providing a release shortly.

**Comment by Dibbidy** [comment]
> Sorry, for the delay. Met with @apolinario at NeurIPS and we are working on a hosting solution for the dataset. We plan on providing a release shortly.

any update on the release?

**Comment by morozig** [comment]
Hi! Are you planning to publish only dataset or trained weights as well? Also can you explain what is the point of non-commercial model if you can use existing sd15 and sdxl models for that already?

**Comment by olliacc** [comment]
Is common canvas vaporware? I heard that it is coming shortly from multiple sources but I'm not seeing it after the paper came out 3 months ago.

**Comment by Dibbidy** [comment]
@Skylion007 any update?

**Comment by olliacc** [comment]
@Skylion007 is this project completely abandoned? I thought there was a release coming shortly.

**Comment by ninjasaid2k** [comment]
Is there any update on the common canvas dataset and model release?

**Comment by Dibbidy** [comment]
@Skylion007 is there still a release planned or is it delayed or shut down?

**Comment by olliacc** [comment]
It's been 3 months since the paper spawned on arxiv with no model or dataset.

**Comment by MHillier98** [comment]
Any updates or timeline for when this might release? 👀

**Comment by Dibbidy** [comment]
> Sorry, for the delay. Met with @apolinario at NeurIPS and we are working on a hosting solution for the dataset. We plan on providing a release shortly.

...

**Comment by olliacc** [comment]
This project is just vaporware isn't it?

**Comment by Landanjs** [comment]
@Skylion007 is still working to get the dataset and model released as soon as possible. Stay tuned!

**Comment by TruthSearcher** [comment]
Does the common canvas use any of the dataset from fondant creative common 25m? https://huggingface.co/datasets/fondant-ai/fondant-cc-25m

**Comment by TruthSearcher** [comment]
@Landanjs Does the common canvas use any of the data from fondant creative common 25m? https://huggingface.co/datasets/fondant-ai/fondant-cc-25m

**Comment by olliacc** [comment]
> @Skylion007 is still working to get the dataset and model released as soon as possible. Stay tuned!

Is it just vaporware? because we haven't see any date or timeline.

**Comment by olliacc** [comment]
I don't think it's going to be released, it's been nearly five months since the paper was on arxiv and we still have no news of any model. It's most likely just vaporware.

**Comment by TruthSearcher** [comment]
> @Skylion007 is still working to get the dataset and model released as soon as possible. Stay tuned!

how's the progress?

**Comment by olliacc** [comment]
> how's the progress?

You were fooled. They are not going to release this vaporware.

**Comment by Skylion007** [comment]
I've begun the upload process to HF Datasets.

**Comment by TruthSearcher** [comment]
> I've begun the upload process to HF Datasets.

do you have the link to the dataset?

**Comment by ninjasaid2k** [comment]
> I've begun the upload process to HF Datasets.

awesome! hope to see it soon. 😊

**Comment by iljung1106** [comment]
> I've begun the upload process to HF Datasets.

How long will it take? more than a month?

**Comment by Skylion007** [comment]
Closed by #143
