### ISSUE TITLE
TypeError("'NoneType' object is not iterable")

### ISSUE THREAD

**Issue by YMKiii** [mosaicml/diffusion#93]
hydra.errors.InstantiationException: Error in call to target 'diffusion.datasets.laion.laion.build_streaming_laion_dataloader':
TypeError("'NoneType' object is not iterable")
full_key: dataset.train_dataset
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 247336) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 247336) exited with code 1

**Comment by coryMosaicML** [comment]
Can you share the part of your training config that calls this dataloader to help figure out why this might be happening?
